### ISSUE TITLE
続 : Trial Stackで最新の日本語Windows Server AMIを使うとcfn-initでエンコーディングエラーが発生する

### ISSUE THREAD

**Issue by stknohg** [stknohg/amazon-workspaces-pack#2]
#1 と同様の事例が再発。
今度は

```
2024-01-19 07:33:50,658 [DEBUG] Running command 0-install-winfeatures
2024-01-19 07:33:50,658 [DEBUG] No test for command 0-install-winfeatures
2024-01-19 07:33:50,705 [INFO] IO redirection is working. Redirecting the output to logs
2024-01-19 07:35:44,880 [ERROR] Unhandled exception during resume: 'utf-8' codec can't decode byte 0x83 in position 80: invalid start byte
Traceback (most recent call last):
  File "cfn-init", line 78, in <module>
  File "cfnbootstrap\construction.pyc", line 187, in resume
  File "cfnbootstrap\construction.pyc", line 581, in run_config
  File "cfnbootstrap\construction.pyc", line 146, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
  File "cfnbootstrap\util.pyc", line 620, in call
  File "cfnbootstrap\util.pyc", line 518, in stdout
  File "cfnbootstrap\util.pyc", line 738, in _ensure_str
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 80: invalid start byte
```

と、`utf8`のエラーが再発する様になってしまっている。

**Comment by stknohg** [comment]
#1 での対応をリバートして対処。

三度再発する様であればファイルリダイレクトに方式を転換する。
- ref: https://dev.classmethod.jp/articles/about-windows-cfn-init-non-ascii-encoding-error/
